### PR TITLE
Fix open/close position accounting

### PR DESCRIPTION
**Pull request by the-orex**
Hello, this PR provide a solution to the following issues:

## Issue 1

The function `add_position` lockup tokens on the `custody`:

```
        stats.locked_amount = math::checked_add(stats.locked_amount, position.locked_amount)?;
```

https://github.com/solana-labs/perpetuals/blob/eb9fe0a6f962665faf736ee068c4d77fd75c825c/programs/perpetuals/src/state/custody.rs#L463C1-L463C95

The problem is that when it's a short position, the `locked_amount` is in collateral unit.

https://github.com/solana-labs/perpetuals/blob/eb9fe0a6f962665faf736ee068c4d77fd75c825c/programs/perpetuals/src/instructions/open_position.rs#L215C2-L215C2

Example: with maxpayoff at 100%, when shorting 1 ETH. Today we're locking up 1500 ETH from the ETH custody (instead of 1 ETH).

--------------

## Issue 2

The checks on `max_position_locked_usd` and `max_total_locked_usd` should be made on the locked token - which is the collateral custody in case of short.

### CODE REVIEW

**Comment by askibin** [comment]
I looked at the PR and I agree that locked amount is not updated properly in global position for shorts or virtual trades. Just two things to note:
1. in open/close position instruction you refactored some code leading to `*custody = collateral_custody.clone();` potentially called twice. Do you know how expensive that copy is? Just trying to understand if shorter code worth it.
2. locked_amount is used to set upper limit for user's pnl. And PnL itself is calculated using the trade token custody only. While the collateral custody is used to calculate interest. You removed locked_amount update for the trade custody (for shorts/virtual) which might lead to an issue. So what if you properly calculate locked_amount for both custodies and update them in add/remove position?

**Comment by mzs-dev** [comment]
One potential solution that we have implemented is to make sure to have a single stable coin custody that acts as default collateral and lockup custody for shorts and virtual assets and then track the assets on collateral custody while tracking collective positions on the target custody so that both interest and collective pnl calculations are accurate

**Comment by askibin** [comment]
> Would you have a specific area in the code for me to look at please regarding the upper limit and PnL please?
it is used here:
https://github.com/solana-labs/perpetuals/blob/master/programs/perpetuals/src/state/pool.rs#L654
https://github.com/solana-labs/perpetuals/blob/master/programs/perpetuals/src/state/pool.rs#L698
collateral custody is the trading token custody for longs so `locked_amount` should be updated properly for the trading custody in the aggregated position

**Comment by askibin** [comment]
I see where your frustration is coming from. There are two different notions of locked amounts. The one that you are referring to in your latest message (what gets locked for potential pnl payoff) happens here:
https://github.com/solana-labs/perpetuals/blob/master/programs/perpetuals/src/instructions/open_position.rs#L302
and already works as you described, i.e. tokens are only locked in the collateral custody, which is a stablecoin for shorts or virtual.
The original locked_amount logic issue which you pointed out: https://github.com/solana-labs/perpetuals/blob/eb9fe0a6f962665faf736ee068c4d77fd75c825c/programs/perpetuals/src/state/custody.rs#L463C1-L463C95
is used for something else. Those stats are used to keep track of the global (aggregated) user position to determine unrealized pnl for all traders combined.
This is the only place where aggregated positions are needed:
https://github.com/solana-labs/perpetuals/blob/master/programs/perpetuals/src/state/pool.rs#L765
The locked amount in aggregated positions is not used to lock tokens for payouts, but rather to determine the upper limits of these payoffs (which is kinda the same, with the only difference is that there is no actual locking in custody, just a variable in position stats that we can access at the time of aggregated pnl calc). And it is used here:
https://github.com/solana-labs/perpetuals/blob/master/programs/perpetuals/src/state/pool.rs#L654
https://github.com/solana-labs/perpetuals/blob/master/programs/perpetuals/src/state/pool.rs#L698

Now, back to the original issue. Aggregated positions should be tracked in trading coin custodies to ensure we can compute pnl correctly. If a trader shorts ETH we need to know what their position size is in ETH. If we update position stats in collateral custody only, we won't be able to compute the pnl. On the other hand, if we keep track of the aggregated position in the trading coin custody only, we won't be able to compute the interest properly for shorts (as it should be based on deposited stablecoin amount and not trade coin). 

One potential solution that was discussed is to keep track of all trade coin positions in stablecoin custody (i.e. via array), which is inefficient. So instead, aggregated positions are tracked in both custodies. Trade token custody is used to compute pnl with zero interest, and stablecoin custody is used to compute interest only with zero pnl. Combined, they are supposed to produce the intended result. Check it out here https://github.com/solana-labs/perpetuals/blob/master/programs/perpetuals/src/state/pool.rs#L766
Since the global position in stablecoin custody is only used for interest calc, locked amount is not used there.

So again, stats for PNL tracking don't affect individual traders' positions and don't lock any funds. These are for aggregated pnl only. But I agree with you that the locked amount for position stats is not updated properly in the case of shorts, as there must be a trade coin amount and not stablecoin. This needs to be fixed.

**Comment by Adrena-Corto** [comment]
Ok thanks for the thorough explanation, that make sense now! No frustration here, but was puzzling to us

**Comment by mzs-dev** [comment]
> > One potential solution that we have implemented is to make sure to have a single stable coin custody that acts as default collateral and lockup custody for shorts and virtual assets and then track the assets on collateral custody while tracking collective positions on the target custody so that both interest and collective pnl calculations are accurate
> 
> @mzs-dev This sentence is beefy, we are not sure we follow 100%. Does that mean you guys lock both collateral (stable) and trade custody assets, and so if so, did you implement borrow fee payments on both assets for the duration of the short?
> 
> That reduce liquidity for very little advantage (for flash trade instead of serving 100 users and getting single interest on USDC form each of them, you'll serve 50 users that pay double interests. You'll loose fees on open/close positions though. Doesn't seems like a good thing for anyone)

Hope your misconception here is also cleared @Adrena-Corto. Extending on @askibin's explanation, we decided to limit stable coin custody to just one and make it the default collateral custody for the interim to avoid storing the conflating position data on collateral custody (in case of shorts/virtual assets) to address the ineffciencies with keeping "track of all trade coin positions in stablecoin custody (i.e. via array), which is inefficient" we have a different solution to model many-many relationship between multiple trade and collateral custodies with an addional state-account as a link allowing us have multiple assets as collateral for each market and trade side. Real trouble starts when you compose over the current program and run into "ix too large" errors. So no, Flash Trade will serve as many users as possible with the best capital efficiency.

**Comment by askibin** [comment]
yeah, in order to track aggregate pnl properly, you need to:
1. keep track of weighted entry price and amount for both longs and shorts in the trading custody (because a major part of pnl depends on entry-exit price difference)
2. separately keep track of the stablecoin collateral amount to calculate interest rate
3. keep track of the position's locked amount in either the trade custody or collateral custody (depending on long/short or virtual) to ensure max profit is calculated properly
So 1. and 2. are easy. While 3. not so. Position stats currently store aggregated positions in trade custodies, but there is no information about which collateral was used (USDC, USDT, etc). Currently, the locked amount represents the trade token amount, which, as you pointed out, is not correct for shorts/virtual. But that was a deliberate decision in favor of simplicity (there is a bug that you uncovered, but it is unrelated to this convo). So the solution would be to do something similar to what Flash did or to track positions with different collateral custody separately. I.e. trade custody will have an array of PositionStats and get_assets_under_management_usd() will loop over and pass proper collateral custody to get_pnl_usd(). The major problem with this is it doesn't scale well to the large number of stablecoin custodies.

**Pull request closed without merging**
